# Generated by Django 4.0.5 on 2022-07-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='file name')),
                ('link', models.CharField(max_length=200, verbose_name='clouded file link')),
                ('encryption_type', models.CharField(default='AES', max_length=10, verbose_name='file encryption')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msgs.message')),
            ],
        ),
    ]
