# Generated by Django 4.0.5 on 2022-07-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('msgs', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msgs.message'),
        ),
    ]
