# Generated by Django 4.0.5 on 2022-07-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(max_length=50, unique=True, verbose_name='bot token'),
        ),
    ]
