version: '3.9'


services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  web:
    build: .
    #    command: python /usr/src/django_messenger/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/django_messenger
    ports:
      - "8000:8000"
volumes:
  postgres_data:
