version: '3.9'


services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
  web:
    build: .
    command: /usr/src/django_messenger/scripts/runserver.sh
    volumes:
      - .:/usr/src/django_messenger
    ports:
      - "8000:8000"
volumes:
  postgres_data:
