# Generated by Django 4.0.5 on 2022-07-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='message type')),
                ('text', models.BinaryField(verbose_name='message text')),
                ('files_password', models.BinaryField(verbose_name='files password')),
                ('encryption_type', models.CharField(default='RSA', max_length=10, verbose_name='message encryption')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chat', verbose_name='chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chatmember', verbose_name='message sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
