# Generated by Django 4.0.5 on 2022-07-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0002_message_sending_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='encryption_type',
            field=models.CharField(default='RSA', max_length=10, null=True, verbose_name='message encryption'),
        ),
        migrations.AlterField(
            model_name='message',
            name='files_password',
            field=models.BinaryField(null=True, verbose_name='files password'),
        ),
    ]
