# Generated by Django 4.0.5 on 2022-07-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0003_alter_message_encryption_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='message text'),
        ),
    ]
