# Generated by Django 4.0.5 on 2022-07-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='private',
            field=models.BooleanField(default=1, verbose_name='private chat'),
            preserve_default=False,
        ),
    ]
